export const URLs = {
        pages: {
                HOME: '/home/',
                LOGIN: '/login/',
                ATTORNEYS: '/attorneys/',
                COMPANY: '/company/',
                CREATE_COMPANY: '/create/company',
                ATTORNEY: '/attorney/',
                CREATE_ATTORNEY: '/create/attorney',
                BLOGS: '/blogs/',
                DONATE: '/donate/',
                CONTACT: '/contact/',
                ABOUT: '/about/',
                TEAM: '/team/',
                USER: '/user/',
                VOLONTEERS: '/volonteers/',
                PARTNERS: '/partners/',
                SPONSORS: '/sponsors/',
                HIEROGLYPHS: '/HIEROGLYPHS/',
                LEGALFUND: '/legalfund/',
                SCHOLARSHIPFUND: '/scholarshipfund/',
                BLOG: '/blog/',
                POST: '/post/',
        },
        services: {
                LAWYER: '/api/lawyer',
                BLOG: '/api/blog',
                USER: '/api/user',
                COMPANY: '/api/company',
                VOLONTEER: '/api/volonteer',
                PARTNER: '/api/partner',
                SPONSOR: '/api/sponsor',
                LANGUAGES: '/api/utils/languages',
                SERVICES: '/api/utils/services',
                COMPANY_TYPES: '/api/utils/companyTypes',
                LOGGED: '/api/login',
                LOGIN: '/api/login'
        }
};